name: Generator
on: [push, pull_request]
permissions:
  contents: read
jobs:
  encrypt-id:
    name: npm-test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run test
